### ISSUE TITLE
all radio stream on youtube not working

### ISSUE THREAD

**Issue by nrafaelos** [jaryn-kubik/aimp_youtubedl#1]
all radio stream on youtube not working Example https://www.youtube.com/watch?v=DSGyEsJ17cI

**Comment by kubik-jaroslav** [comment]
What versions of the plugin, youtube-dl (you can see that in Plugins -> Youtube-DL)  and AIMP are you using? Have you fiddled with the settings at all?
Because the link plays for me just fine.
