### ISSUE TITLE
Could not load Python.Runtime

### ISSUE THREAD

**Issue by cloewen8** [jaryn-kubik/aimp_youtubedl#11]
When launching AIMP after installing the plugin, I get the following error dialog:

> Could not load file or assembly 'Python.Runtime, Version=3.7.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

The plugin shows up in the list of plugins but AIMP reports it won't be used. I am using AIMP 4.60 on Windows 10 (build 18363.959) and I do have the recommended .net runtime. Am I missing something?

**Comment by kubik-jaroslav** [comment]
What version of the plugin are you using?
Does the file "Python.Runtime" exist in C:\Program Files (x86)\AIMP\Plugins\aimp_youtubedl\Python.Runtime.dll?

I've added some logging to the part that searches for dlls. Try updating to 2.0.3 and paste the contents of the log file after this error appears (C:\Users\Jaryn\AppData\Roaming\AIMP\aimp_youtubedl\*.log).

**Comment by cloewen8** [comment]
Sorry for that delay. I just installed version 2.0.3 and it is in that folder with the "Python.Runtime" file. After running it, the same error dialog appears. The log files are below.

[aimp_youtubedl_AIMPac_20200728_023003.log](https://github.com/jaryn-kubik/AimpYouTubeDL/files/4990929/aimp_youtubedl_AIMPac_20200728_023003.log)
[aimp_youtubedl_AIMPate_20200728_022919.log](https://github.com/jaryn-kubik/AimpYouTubeDL/files/4990930/aimp_youtubedl_AIMPate_20200728_022919.log)
[aimp_youtubedl_AIMP_20200728_141513.log](https://github.com/jaryn-kubik/AimpYouTubeDL/files/4990931/aimp_youtubedl_AIMP_20200728_141513.log)

**Comment by kubik-jaroslav** [comment]
Thanks for the logs, based on what i googled it looks like some security error when windows blocks using dlls downloaded from internet and then unzipped for some reason.

Try 2.0.4, I embedded the Python.Runtime.dll inside the aimp_youtube.dll so it's just one file now, should prevent all of these errors.

**Comment by cloewen8** [comment]
Thank you, that did appear to fix the problem.
