### ISSUE TITLE
 Bug: 'DownloadError: ERROR: Signature extraction failed: Traceback'

### ISSUE THREAD

**Issue by tag27** [jaryn-kubik/aimp_youtubedl#12]
Is this a bug in the plugin or is it from YouTube DL itself? (Sorry for bad English, I'm using Google Translate)
![88597194-1b6e0900-d03d-11ea-95d2-9e0c20677b1f](https://user-images.githubusercontent.com/68751594/88597585-ee6e2600-d03d-11ea-95eb-f44df8a37aa4.png)

I have the latest version of the plugin installed, I even updated it yesterday

**Comment by kubik-jaroslav** [comment]
youtube-dl issue, see https://github.com/ytdl-org/youtube-dl/blob/master/ChangeLog, they just released an update
