### ISSUE TITLE
Access Violation Error

### ISSUE THREAD

**Issue by w-** [jaryn-kubik/aimp_youtubedl#2]
![image](https://user-images.githubusercontent.com/357317/69693758-169d3200-1109-11ea-9304-776ba4e440e2.png)

whenever i add a youtube link i get the error in screenshot above. The link loads fine tho and i'm able to playback.

on  
plugin youtube-dl v1.0.1
youtube-dl v2019.11.22  

didn't change any settings

thanks in advance for the plugin!

**Comment by GlitchyPSIX** [comment]
Hello, I also encountered this issue.

**Comment by kubik-jaroslav** [comment]
Should be fixed in v1.0.2.
