### ISSUE TITLE
Plugin loads without errors, but no change is made

### ISSUE THREAD

**Issue by quagsirus** [jaryn-kubik/aimp_youtubedl#3]
The settings menu does not appear, and there is no way to add a youtube url

![image](https://user-images.githubusercontent.com/7071791/70864143-345ef980-1f47-11ea-8146-e83533c0dde8.png)

Both dependencies are installed on my PC, but when I inspect the Python.Runtime.dll, it appears 2 dlls are missing

![image](https://user-images.githubusercontent.com/7071791/70864159-6a03e280-1f47-11ea-93c1-544bdea58f4e.png)

**Comment by kubik-jaroslav** [comment]
Is the plugin enabled in Options -> Plugins -> YouTube-DL?
Are you using AIMP v4.5+?
Did you extract all the files (including the "python" directory)?
There should also be some log file in "C:\Users\{username}\AppData\Roaming\AIMP\aimp_youtubedl\".

**Comment by kubik-jaroslav** [comment]
No response for half a year, closing.
