### ISSUE TITLE
Shows me an error when i try to run it via AIMP.

### ISSUE THREAD

**Issue by Fujosej** [jaryn-kubik/aimp_youtubedl#5]
Basically it shows me this error everytime i try to feed it a youtube link.

<details>
<summary>error</summary>

![image](https://user-images.githubusercontent.com/37980944/78535797-6eedea00-77f5-11ea-9fd6-656e93d5433d.png)

</details>
I have an AIMP 4.6 build 2180

Here is the log , sorry if it's in russian , but i think the core of it should be understandable
[aimp_youtubedl.log](https://github.com/jaryn-kubik/aimp_youtubedl/files/4436851/aimp_youtubedl.log)

Don't really know what could be the problem here. 

<details>
<summary>Visual C++ versions.</summary>

![image](https://user-images.githubusercontent.com/37980944/78536263-3bf82600-77f6-11ea-960e-892da37a7dc5.png)

</details>

<details>
<summary>Framework version</summary>

![image](https://user-images.githubusercontent.com/37980944/78535140-57fac800-77f4-11ea-9539-7d3918d8b0d0.png)
![image](https://user-images.githubusercontent.com/37980944/78535162-647f2080-77f4-11ea-87df-88c8c25dc3ab.png)

</details>

I think i have all the Requirements.

**Comment by ArtemIzmaylov** [comment]
@jaryn-kubik 
Seems I have found root of the issue. It happens on attempt to add URL to playlist if current folder differs from the "[AIMP]\Plugins\".

**Comment by kubik-jaroslav** [comment]
@ArtemIzmaylov
"current folder differs from the "[AIMP]\Plugins""
I don't know what you mean by this. What does current folder mean here? How do I change it to reproduce this?

Anyway based on the exception I tried to implement a fix in 1.0.3, but I can't verify if it works, cause I don't know how to reproduce this.

**Comment by kubik-jaroslav** [comment]
From v2.0.4+ this should no longer be a problem since it's just one dll.
