### ISSUE TITLE
yandexmusic

### ISSUE THREAD

**Issue by fastbeak** [jaryn-kubik/aimp_youtubedl#7]
Hi, can you add authorization in the yandexmusic service to the plugin?
Without authorization, you cannot listen to your playlists.
Thanks for the plugin)

**Comment by andreyxb97** [comment]
I agree, please add authorization for Yandex music, you can only listen to Yandex music for 30 seconds without logging in

**Comment by kubik-jaroslav** [comment]
Should be possible in 1.0.3 thanks to #8.
You need to add file cookies.txt to C:\Users\[User]\AppData\Roaming\AIMP\aimp_youtubedl\

See https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl on how to get the cookies.txt file.

**Comment by andreyxb97** [comment]
Thank you very much, it works great

вс, 14 июн. 2020 г. в 01:00, jaryn-kubik <notifications@github.com>:
